name: Run and Test library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout files"
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore EzRabbitMQ.sln
    - name: Copy Readme into library
      uses: canastro/copy-action@0.0.2
      with:
        source: ./README.md
        target: ./Src/EzRabbitMQ/readme.md
    - name: Build
      run: dotnet build --no-restore
    - uses: mer-team/rabbitmq-mng-action@v1.2
      with:
        RABBITMQ_TAG: '3-management-alpine'
    - name: Unittests
      uses: zyborg/dotnet-tests-report@ce730c068bb73480dcb37c02d40890bf8b44c953
   
   
